language: python

python:
  - 3.5

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - python setup.py install
  - pip list

script:
    - echo $PWD
    - pytest --cov=aos --cov-report=xml --cov-config tests/.coveragerc

after_success:
  - codecov