language: python

python:
  - 3.5

branches:
  only:
    - master

before_install:
  - export EIGEN_DIR=$PWD/eigen/
  - export CMAKE_VERBOSE_MAKEFILE=1
  - sudo apt-get install -y libfftw3-dev
  - sudo apt-get install -y libeigen3-dev
  - pip install pybind11
  - pip install galsim
  - git clone https://github.com/jmeyers314/batoid.git
  - cd batoid
  - python setup.py install
  - cd ..
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip list

install:
  - python setup.py install
  - pip list

script:
    - echo $PWD
    - pytest --cov=aos --cov-report=xml --cov-config tests/.coveragerc

after_success:
  - codecov