language: python

python:
  - 3.6.7

branches:
  only:
    - master

before_install:
  - export EIGEN_DIR=$PWD/eigen/
  - export CMAKE_VERBOSE_MAKEFILE=1
  - sudo apt-get install -y libfftw3-dev
  - sudo apt-get install -y libeigen3-dev
  - pip install pybind11
  - pip install galsim
  - cd ..
  - git clone --recurse-submodules https://github.com/jmeyers314/batoid.git
  - cd batoid
  - git pull origin releases/0.1:releases/0.1
  - git checkout releases/0.1
  - python setup.py install
  - cd ../ActiveOpticsSimulator
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip list

install:
  - python setup.py develop
  - pip list

script:
    - echo $PWD
    - pytest --cov=aos --cov-report=xml --cov-config tests/.coveragerc tests
    - cat coverage.xml

after_success:
  - codecov -t 1e8eae0c-e424-43cb-9bc8-fb87d698fffa
