language: python

python:
  - 3.5

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  #- travis_wait 30 pip install -U -r test_requirements.txt
  - pip install -r test_requirements.txt
  # - pip install matplotlib 
  - python setup.py install
  - pip list

script:
    # - python setup.py install
    - echo $PWD
    - pytest --cov=aos --cov-report=xml --cov-config tests/.coveragerc

after_success:
  - codecov